### PR TITLE
Fixed pin names in 4164 symbols

### PR DESCRIPTION
**Pull request by gorlik**
The pins were incorrectly labeled as D0/D1 instead of DO/DI

### CODE REVIEW

**Comment by gorlik** [comment]
more changes to reduce the number of ERC warnings

**Comment by bwack** [comment]
Hi. Would you like to have some fixed pulled into the repo ? There are alot of more stuff than what the title of this pull request suggests. New schemactics files, renaming of files. I'll have a look.

**Comment by bwack** [comment]
When I open the schema I see only [??] as symbols. I'm guessing that when you renamed the schematics library file, you added it as a global property, not as a project properties. Anyway. There are a few changes here that I don't like. If you could just make a pull request for the first changes you made. DI and DO, the ERC stuff , then I can pull it in.

**Comment by gorlik** [comment]
I apologize. I meant to send only relevant fixes not the style/name changes. Somehow github decided to include all int he pull request (likely a user error though).
My original intent was to pull up to [d4b68cc](https://github.com/bwack/C64-250407-Replica-KiCad/pull/5/commits/d4b68cc823c45c4d64670743e7bfda3c7328950f)
Could you check if that works?

**Comment by bwack** [comment]
I see. Super, I'll see how I can pull in up to that commit :+1:

**Comment by bwack** [comment]
I've experimented on a local git repo:
Can you do this ?

assuming you have nothing new to commit:
(oh I assume you use git by command line..)
```
git checkout -b mynewbranch # create a new branch
git checkout main
git reset d4b68cc823c45c4d64670743e7bfda3c7328950f
git --force push
```

**Comment by gorlik** [comment]
I am sorry but I could not figure out how to get the tree to be what I expected.
I thought about creating a second fork but github does not allow that.
I am planning to create a new repo, delete the fork and re-create the fork and only make/commit the relevant changes to the new fork.

It's likely all this could be done with branches, but I don't seem to be good enough with git to handle it. 
BTW: my last commit was somehow automatically added to this pull request as well.

**Comment by gorlik** [comment]
let me know if it worked.
BTW: are you interested in the 250525 and 407466 schematics?

**Comment by bwack** [comment]
Thanks again ! :)
Regarding 250425 and 250466 I'd be interested in, but not in this repo. Maybe you could make a repository for them, and I can link to them from this repo's readme.md page ?

**Pull request merged**
